#!/usr/bin/env bash
# keyed to super-0
set -e

WINDOW_STR="VSCodium"
WM_CLASS="vscodium.VSCodium"

# we use WM_CLASS as well as WINDOW_STR to avoid matching on random website title text

# if window is open but not active, switch to it.
# otherwise minimize it
# https://superuser.com/questions/142945/bash-command-to-focus-a-specific-window
#https://askubuntu.com/questions/4876/can-i-minimize-a-window-from-the-command-line

NAME=$(xdotool getwindowfocus getwindowname)

# first find window id
# https://unix.stackexchange.com/questions/109835/how-do-i-use-cut-to-separate-by-multiple-whitespace
WINDOW_ID=$(wmctrl -xl | grep "$WINDOW_STR" | tr -s ' ' | cut -d ' ' -f 1,3 | grep $WM_CLASS | cut -d ' ' -f 1)

RC=0
# look for substring match
if [[ "$NAME" == *"$WINDOW_STR"* ]]; then
    wmctrl -i -a "$WINDOW_ID" -b add,hidden || RC=$?
    #espeak "hiding"
else
    wmctrl -i -a "$WINDOW_ID" || RC=$?
    #espeak "restoring $RC"
fi

# https://stackoverflow.com/questions/26675681/how-to-check-the-exit-status-using-an-if-statement
if [[ "${RC}" == 1 ]]; then
    echo "starting vscodium"
    codium
fi

