#!/usr/bin/env bash
# open teams

# keyed to super-1
set -e

# if python-fire window is open, switch to it
# https://superuser.com/questions/142945/bash-command-to-focus-a-specific-window

WINDOW_STR="Microsoft Teams"

#todo: this has a bug that it will open another copy of chrome teams if the tab isn't active in the already open teams

# if window is open but not active, switch to it.
# otherwise minimize it
# https://superuser.com/questions/142945/bash-command-to-focus-a-specific-window
#https://askubuntu.com/questions/4876/can-i-minimize-a-window-from-the-command-line

NAME=$(xdotool getwindowfocus getwindowname)

# look for substring match
if [[ "$NAME" == *"$WINDOW_STR"* ]]; then
    wmctrl -a $WINDOW_STR -b add,hidden && true
    #espeak "hiding"
else
    wmctrl -a $WINDOW_STR && true
    #espeak "restoring"
fi
RC=$?

# https://stackoverflow.com/questions/26675681/how-to-check-the-exit-status-using-an-if-statement
if [[ "${RC}" == 1 ]]; then
    echo "starting teams"
    google-chrome https://teams.microsoft.com
fi

