#!/usr/bin/env bash
# open krita and maximize (expected to be always on tablet, so minimize toggle isn't needed)

#set -x
set -e

# if window is open, switch to it
# https://superuser.com/questions/142945/bash-command-to-focus-a-specific-window

WINDOW_STR="Krita"
WM_CLASS="krita.krita"

# this may match with the wrong window if a tab in firefox for example has the words MicrosoftTeams in it. It even seems to ignore the space at the start.


# if window is open but not active, switch to it.
# otherwise minimize it
# https://superuser.com/questions/142945/bash-command-to-focus-a-specific-window
#https://askubuntu.com/questions/4876/can-i-minimize-a-window-from-the-command-line

NAME=$(xdotool getwindowfocus getwindowname)

# first find window id
# https://unix.stackexchange.com/questions/109835/how-do-i-use-cut-to-separate-by-multiple-whitespace
WINDOW_ID=$(wmctrl -xl | tr -s ' ' | cut -d ' ' -f 1,3 | grep $WM_CLASS | cut -d ' ' -f 1)


# check if window we're looking for is already active
# look for substring match
#if [[ "$NAME" == *"$WINDOW_STR"* ]]; then
#    wmctrl -i -a $WINDOW_ID -b add,hidden && true
#    #espeak "hiding"
#    echo hiding
#else
    wmctrl -i -a $WINDOW_ID && true
    RC=$?
    #espeak "restoring"
	echo restoring
#fi

# https://stackoverflow.com/questions/26675681/how-to-check-the-exit-status-using-an-if-statement
if [[ "${RC}" == 1 ]]; then
    echo "starting krita"
    /home/poleguy/Applications/krita-5.2.6-x86_64_b91deea105204592bed527d811426f67.appimage
fi

