#!/usr/bin/env bash
# keyed to super-0
set -e

WINDOW_STR="python-fire"

# if window is open but not active, switch to it.
# otherwise minimize it
# https://superuser.com/questions/142945/bash-command-to-focus-a-specific-window
#https://askubuntu.com/questions/4876/can-i-minimize-a-window-from-the-command-line

NAME=$(xdotool getwindowfocus getwindowname)

# look for substring match
if [[ "$NAME" == *"$WINDOW_STR"* ]]; then
    wmctrl -a $WINDOW_STR -b add,hidden && true
    #espeak "hiding"
else
    wmctrl -a $WINDOW_STR && true
    #espeak "restoring"
fi
RC=$?

# https://stackoverflow.com/questions/26675681/how-to-check-the-exit-status-using-an-if-statement
if [[ "${RC}" == 1 ]]; then
    echo "starting python"
    xfce4-terminal --command=python3 --title=python-fire
    # set terminal window to python3-fire to be unique and easy to script
fi

